city = ["北京","上海","广东"]
city.append("武汉")
city.append("天津")
city.append("呼和浩特")
city.append("福州")
city.append("昆明")
city.append("杭州")
city.append("拉萨")
city.append("乌鲁木齐")
city.append("重庆")
city.append("台北")
city.append("成都")
city.append("长沙")
city.append("西宁")
city.append("重庆")
city.append("兰州")
city.append("海口")
city.append("银川")
city.append("南昌")
city.append("郑州")
city.append("合肥")
city.append("石家庄")
city.append("桂林")
city.append("贵阳")
city.append("黑龙江")
city.append("沈阳")
city.append("长春")
city.append("济南")
city.append("山西")
city.append("西安")
# print(len(city))
# print("移除前",city)
# city.remove("广东")
# print("移除后",city)
# city.insert(1,"广东")
# print("升级后排序",city)
def swap(city,a,b):
    first = city.pop(a)
    second = city.pop(b-1)

    city.insert(a,second)
    city.insert(b,first)
    return city
a = 2
b = 3
print(swap(city,a-1,b-1))